//路由配置信息，本文件中的路由组件都采用了懒加载的形式
export default [
    {
        name:"center",
        path:"/center",
        component:()=>import("@/pages/Center"),
        meta:{
            isShow:false,//判断页面跳转到该组件时Footer组件是否显示，true显示，false不显示
        },
        //配置二级路由组件
        children:[
            {
                path:"myorder",
                component:()=>import("@/pages/Center/MyOrder"),
            },
            {
                path:"grouporder",
                component:()=>import("@/pages/Center/GroupOrder"),
            },
            {
                //重定向
                path:"/center",
                redirect:"/center/myorder",
            },
        ],  
    },

    {
        name:"paysuccess",
        path:"/paysuccess",
        component:()=>import("@/pages/PaySuccess"),
        meta:{
            isShow:true,//判断页面跳转到该组件时Footer组件是否显示，true显示，false不显示
        },
        //只有从支付页面跳转才能放行
        beforeEnter: (to, from, next) => {
            if(from.path=="/pay"){
                next();
            }else{
                next(false);//跳转到当前页面
            }
        }
    },
    {
        name:"pay",
        path:"/pay",
        component:()=>import("@/pages/Pay"),
        meta:{
            isShow:false,//判断页面跳转到该组件时Footer组件是否显示，true显示，false不显示
        },
        //只有来自交易页面trade的才放行
        beforeEnter: (to, from, next) => {
            if(from.path=="/trade"){
                next();
            }else{
                next(false);//跳转到当前页面
            }
        }
    },
    {
        name:"trade",
        path:"/trade",
        component:()=>import("@/pages/Trade"),
        meta:{
            isShow:false,//判断页面跳转到该组件时Footer组件是否显示，true显示，false不显示
        },
        //设置trade的路由独享守卫，控制只有从加入购物车成功页面才能放行
        beforeEnter: (to, from, next) => {
            if(from.path=="/shopcart"){
                next();
            }else{
                next(false);//跳转到当前页面
            }
        }
    },

    {
        name:"shopcart",
        path:"/shopcart",
        component:()=>import("@/pages/ShopCart"),
        meta:{
            isShow:false,//判断页面跳转到该组件时Footer组件是否显示，true显示，false不显示
        },
    },
    {
        name:"addcartsuccess",
        path:"/addcartsuccess",
        component:()=>import("@/pages/AddCartSuccess"),
        meta:{
            isShow:true,//判断页面跳转到该组件时Footer组件是否显示，true显示，false不显示
        },
    },
    {
        path:"/detail/:skuId",
        component:()=>import("@/pages/Detail"),
        meta:{
            isShow:true,//判断页面跳转到该组件时Footer组件是否显示，true显示，false不显示
        },
    },
    {
        path:"/home",
        component:()=>import("@/pages/Home"),
        meta:{
            isShow:true,//判断页面跳转到该组件时Footer组件是否显示，true显示，false不显示
        },
    },

    {
        name:"search",
        path:"/search/:keyword?",
        component:()=>import("@/pages/Search"),
        meta:{
            isShow:true,
        },
    },
    {
        path:"/login",
        component:()=>import("@/pages/Login"),
        meta:{
            isShow:false,
        },
    },
    {
        path:"/register",
        component:()=>import("@/pages/Register"),
        meta:{
            isShow:false,
        },
    },
    //重定向，当项目跑起来的时候，访问/。马上让页面重定向到首页
    {
        path:"/",
        redirect:"/home",
    },
]